
export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const RESET_STATE = 'RESET_STATE';


export const ACTIONS = {
	FETCH_PLACES,
	FETCH_PLACES_SUCCESS,
	FETCH_PLACES_FAILURE,
	RESET_STATE,
};